### ISSUE TITLE
Failed to load the nucleus package

### ISSUE THREAD

**Issue by sopsmattw** [faceyspacey/nucleus#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [nucleus](https://github.com/faceyspacey/nucleus) package, v0.3.0
### Stack Trace

Failed to load the nucleus package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/matt/.atom/packages/nucleus/lib/views/forms/abstract_form.coffee:4:199)
    at /Users/matt/.atom/packages/nucleus/lib/views/forms/abstract_form.coffee:9:5
    at Object.<anonymous> (/Users/matt/.atom/packages/nucleus/lib/views/forms/abstract_form.coffee:116:5)
    at Object.<anonymous> (/Users/matt/.atom/packages/nucleus/lib/views/forms/abstract_form.coffee:120:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-printer, vundefined
language-perl-template-toolkit, v0.1.0
lib, vundefined
menus, vundefined
node_modules, vundefined
nucleus, v0.3.0
remote-edit, v1.7.2

# Dev
No dev packages
```

**Comment by prettyamfora** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [nucleus](https://github.com/faceyspacey/nucleus) package 0.3.0


### Stack Trace

Failed to load the nucleus package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at extend (/packages/nucleus/lib/views/forms/abstract_form.coffee:1:1)
    at /packages/nucleus/lib/views/forms/abstract_form.coffee:4:7
    at /packages/nucleus/lib/views/forms/abstract_form.coffee:52:13)
    at /packages/nucleus/lib/views/forms/abstract_form.coffee:1:1)
    at /packages/nucleus/lib/views/forms/abstract_form.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:146745)
    at /packages/nucleus/lib/views/forms/enter.coffee:1:12)
    at /packages/nucleus/lib/views/forms/enter.coffee:1:1)
    at /packages/nucleus/lib/views/forms/enter.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:146745)
    at /packages/nucleus/lib/nucleus.coffee:1:17)
    at /packages/nucleus/lib/nucleus.coffee:1:1)
    at /packages/nucleus/lib/nucleus.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:1:721712)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:3299000)
    at measure (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:3285540)
    at Package.measure (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:3284372)
    at Package.load (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:3285113)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:381274)
    at PackageManager.loadPackage (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:380002)
    at PackageManager.atom.packages.loadPackage (/packages/atom-ide-ui/modules/nuclide-commons-atom/FeatureLoader.js:527:32)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:382574)
    at ~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:943557
    at r (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:938163)
    at o (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:1122275)
    at ChildProcess.n.process.on.e (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:1122481)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
     -9:01.4.0 core:confirm (input.hidden-input)
  8x -7:57.7.0 core:backspace (input.hidden-input)
     -7:16.2.0 core:confirm (textarea.xterm-helper-textarea)
     -7:02.8.0 atom-ide-terminal:new-terminal (div.panels-item)
     -7:00.6.0 core:paste (textarea.xterm-helper-textarea)
  2x -6:49.7.0 core:backspace (textarea.xterm-helper-textarea)
     -5:38.9.0 debugger:show-attach-dialog (ul.list-inline.tab-bar.inset-panel)
     -5:26.1.0 core:cancel (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui.teletype-Authenticated)
  2x -5:18 pane:close (div.item-views)
  2x -2:53.4.0 core:paste (div.placeholder-text)
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
autoreload-package-service 0.0.4 
box-edit 0.1.3 
busy-signal 2.0.1 
hey-pane 1.2.0 
html-include-resource 1.3.0 
Hydrogen undefined 
ide-rust 0.21.2 
intentions 1.1.5 
language-apt 1.0.0 
language-caper 1.1.0 
linter 2.3.1 
linter-package-json-validator 2.0.0 
linter-ui-default 1.8.1 
my-package 0.0.0 
nucleus 0.3.0 
nuclide-test-runner-cmd 0.1.0 
package-json5 1.0.1 
package-script-runner 1.0.0 
rust-lang 0.6.0 
scroll-through-time 0.3.1 
simplified-russian-menu 1.3.0 
teletype 0.13.4 
tool-bar 1.3.0 
wraptor 0.2.1 
zentabs 0.8.9 
```

**Comment by cat5lyst** [comment]
Atom :  1.55.0

Electron : 6.1.12
Chrome : 76.0.3809.146
Node : v12.4.0

NUCLEUS : 0.3.0

Failed to load the nucleus package

Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at extend (file:///C:/Users/bSean/.atom/packages/nucleus/lib/views/forms/abstract_form.coffee:1:1)
    at file:///C:/Users/bSean/.atom/packages/nucleus/lib/views/forms/abstract_form.coffee:4:7
    at Object.<anonymous> (file:///C:/Users/bSean/.atom/packages/nucleus/lib/views/forms/abstract_form.coffee:52:13)
    at Object.<anonymous> (file:///C:/Users/bSean/.atom/packages/nucleus/lib/views/forms/abstract_form.coffee:1:1)
    at Object.<anonymous> (file:///C:/Users/bSean/.atom/packages/nucleus/lib/views/forms/abstract_form.coffee:1:1)
    at Module.get_Module._compile (C:\Users\bSean\AppData\Local\atom\app-1.55.0\resources\app\static\<embedded>:11:147404)
    at Object.value [as .coffee] (C:\Users\bSean\AppData\Local\atom\app-1.55.0\resources\app\static\<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (file:///C:/Users/bSean/AppData/Local/atom/app-1.55.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\bSean\AppData\Local\atom\app-1.55.0\resources\app\static\<embedded>:11:146720)
    at Object.<anonymous> (file:///C:/Users/bSean/.atom/packages/nucleus/lib/views/forms/enter.coffee:1:12)
    at Object.<anonymous> (file:///C:/Users/bSean/.atom/packages/nucleus/lib/views/forms/enter.coffee:1:1)
    at Object.<anonymous> (file:///C:/Users/bSean/.atom/packages/nucleus/lib/views/forms/enter.coffee:1:1)
    at Module.get_Module._compile (C:\Users\bSean\AppData\Local\atom\app-1.55.0\resources\app\static\<embedded>:11:147404)
    at Object.value [as .coffee] (C:\Users\bSean\AppData\Local\atom\app-1.55.0\resources\app\static\<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (file:///C:/Users/bSean/AppData/Local/atom/app-1.55.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\bSean\AppData\Local\atom\app-1.55.0\resources\app\static\<embedded>:11:146720)
    at Object.<anonymous> (file:///C:/Users/bSean/.atom/packages/nucleus/lib/nucleus.coffee:1:17)
    at Object.<anonymous> (file:///C:/Users/bSean/.atom/packages/nucleus/lib/nucleus.coffee:1:1)
    at Object.<anonymous> (file:///C:/Users/bSean/.atom/packages/nucleus/lib/nucleus.coffee:1:1)
    at Module.get_Module._compile (C:\Users\bSean\AppData\Local\atom\app-1.55.0\resources\app\static\<embedded>:11:147404)
    at Object.value [as .coffee] (C:\Users\bSean\AppData\Local\atom\app-1.55.0\resources\app\static\<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (file:///C:/Users/bSean/AppData/Local/atom/app-1.55.0/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (C:\Users\bSean\AppData\Local\atom\app-1.55.0\resources\app\static\<embedded>:1:736637)
The error was thrown from the nucleus package.
